version: '3.9'

services:
  backend:
    container_name: backend
    restart: always
    build:
      context: ./backend
    volumes:
      - /usr/src/backend/node_modules
      - ./backend:/usr/src/backend
    ports:
      - 5000:5000
      - 9229:9229
    links:
      - mongo
    environment:
      - PORT=5000
      - DATABASE_URL=mongodb://mongo:27017/backend

  frontend:
    container_name: frontend
    restart: always
    build:
      context: ./frontend
    volumes:
      - /usr/src/frontend/node_modules
      - ./frontend:/usr/src/frontend
    ports:
      - '3100:3000'
    environment:
      - API_URL=http://localhost:5000
    links:
      - backend

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - '27017:27017'

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - '8081:8081'